INFO:__main__:Starting new job for input: /workspaces/microbe_masst/examples/small.mgf
0it [00:00, ?it/s]3it [00:00, 508.69it/s]
INFO:masst_batch_client:Running fast microbe masst on input n=3 spectra (total with already finished was 3 spectra)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fasst.gnps2.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fasst.gnps2.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fasst.gnps2.org:443
DEBUG:urllib3.connectionpool:https://fasst.gnps2.org:443 "POST /search HTTP/11" 200 35969
DEBUG:urllib3.connectionpool:https://fasst.gnps2.org:443 "POST /search HTTP/11" 200 6889
DEBUG:root:fastMASST response=200
DEBUG:root:fastMASST response=200
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fasst.gnps2.org:443
DEBUG:urllib3.connectionpool:https://fasst.gnps2.org:443 "POST /search HTTP/11" 200 8644
DEBUG:root:fastMASST response=200
DEBUG:masst_client:Exporting microbeMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/microbe_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/microbe_masst_table.csv'
DEBUG:masst_client:Exporting plantMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/plant_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/plant_masst_table.csv'
DEBUG:masst_client:Exporting tissueMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/tissue_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/tissue_masst_table.csv'
DEBUG:masst_client:Exporting foodMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/food_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/food_masst_table.csv'
DEBUG:masst_client:Exporting personalCareProductMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/personalCareProduct_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/personalCareProduct_masst_table.csv'
DEBUG:masst_client:Exporting microbiomeMASST 208
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/microbiome_masst_table.tsv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 149, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file, sep="\t")
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/microbiome_masst_table.tsv'
DEBUG:masst_client:Exporting combined tree 208
DEBUG:urllib3.connectionpool:https://fasst.gnps2.org:443 "POST /search HTTP/11" 200 177203940
DEBUG:root:fastMASST response=200
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): fasst.gnps2.org:443
DEBUG:urllib3.connectionpool:https://fasst.gnps2.org:443 "POST /search HTTP/11" 200 96606
DEBUG:root:fastMASST response=200
DEBUG:masst_client:Exporting microbeMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/microbe_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/microbe_masst_table.csv'
DEBUG:masst_client:Exporting plantMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/plant_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/plant_masst_table.csv'
DEBUG:masst_client:Exporting tissueMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/tissue_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/tissue_masst_table.csv'
DEBUG:masst_client:Exporting foodMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/food_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/food_masst_table.csv'
DEBUG:masst_client:Exporting personalCareProductMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/personalCareProduct_masst_table.csv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 151, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/personalCareProduct_masst_table.csv'
DEBUG:masst_client:Exporting microbiomeMASST 
ERROR:masst_tree:[Errno 2] No such file or directory: '../data/microbiome_masst_table.tsv'
Traceback (most recent call last):
  File "/workspaces/microbe_masst/code/masst_tree.py", line 46, in create_enriched_masst_tree
    results_df = export_metadata_matches(special_masst, matches_df, out_counts_file)
  File "/workspaces/microbe_masst/code/masst_tree.py", line 149, in export_metadata_matches
    metadata_df = pd.read_csv(metadata_file, sep="\t")
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/opt/conda/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '../data/microbiome_masst_table.tsv'
DEBUG:masst_client:Exporting combined tree 
